### ISSUE TITLE
Setting up a tourney and tables

### ISSUE THREAD

**Issue by mbenedettini** [pokermania/pokernetwork#1]
Hi:

I want to give pokernetwork a try, but I'm not able to find the way to set up a tourney and its tables, so that I can later play via either pokercli or jpoker.

Can anybody please point me in the right direction?
Thanks in advance,
Mariano.

**Comment by jakob-stoeck** [comment]
Did you run the installation instructions from the readme? Do normal tables outside of tourneys work?

**Comment by mbenedettini** [comment]
Yes I ran the installation instructions and some db tables have been populated (for instance, table users contains 3 rows).

Perhaps I didn't explain myself properly. I couldn't setup a poker table, either inside a tourney or not.
Jpoker admin interface looks broken, as it wants to perform sql queries via /cgi-bin, and I'm not being able to find any other admin interface (working or not).

**Comment by ruxkor** [comment]
The `jpoker` admin interface is currently unmaintained, (feel free to issue a pull request if you manage to improve it). Why not change the tables directly in the database?

**Comment by mbenedettini** [comment]
Changing tables via sql was my last resort but I'll try that way.

I promise to issue a pull request of any improvement I manage to make.

Thanks,
Mariano.
