### ISSUE TITLE
Debian build fails

### ISSUE THREAD

**Issue by AeonLerau** [pokermania/pokernetwork#2]
I've tried to build a debian package of pokernetwork on Ubuntu 14.04 with the command: dpkg-deb --build debian but the directory structure and the control file don't seem to follow Debian standards.  I get this error: failed to open package info file `debian/DEBIAN/control' for reading: No such file or directory.  Could someone describe to me how to build the source into a debian package?

**Comment by hwmrocker** [comment]
we are using `dpkg-buildpackage -b` to build a debian package. Our build script is bit longer it generates the `debian/changelog` file from the git history before the actual building and does some other stuff. You can try to fake this file your self and then run this command.

I will try to add this file to repo again, but i have to make sure that our build process will not be harmed.

**Comment by AeonLerau** [comment]
Thank you,  with that I was able to build all the packages related to poker network, however, when I install poker network with the package installer I receive the error: dependency is not satisfiable which is related to python-simple-db-migrate.  I installed python-simple-db-migrate with pip successfully but the package installer continues to report that the dependency is not satisfiable.  What could be the problem?

**Comment by AeonLerau** [comment]
hwmrocker, I was able to resolve the issue with simple-db-migrate.  Instead of installing with pip; It was as "simple" as building it into a Debian package from source and installing via a package manager :-).  The pokernetwork server installed easily after that.  Question:  Does your organisation maintain a client that I can use to test the pokerserver? Or can you recommend some client?

**Comment by hwmrocker** [comment]
Thats nice to hear :smile:

the default javascript client was once https://github.com/pokermania/jpoker but it is currently not maintained so it might not work out of the box. In case you are (a bit) familiar with twisted https://github.com/pokermania/pokernetwork/blob/master/pokernetwork/pokerclient.py is the way to build your own client.
